### ISSUE TITLE
Placeholder Mixin not working correctly

### ISSUE THREAD

**Issue by erwstout** [erwstout/sugar#3]
When using `@include placeholder` styles are not being applied.

**Comment by erwstout** [comment]
Cannot be applied to individual form items. For instance, must just be included. Such as:

``` scss
footer{
    // style placeholders for footer
    @include placeholder{
    color: $lightgrey;
    };
}
```
